 CREATE TABLE ADMINS(
 	ADMIN_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	USER_NAME VARCHAR(255) NOT NULL, 
	PASSWORD VARCHAR(255) NOT NULL,
	AUTHORITY VARCHAR(50) NOT NULL,
	IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,	
	UNIQUE UQ_ADMINS_1 (USER_NAME),
	PRIMARY KEY (ADMIN_ID)
);
CREATE TABLE USERS (
  USER_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  EMAIL_ADDR VARCHAR(255) NOT NULL,
  FIRST_NAME VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(255),
  IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,  
  unique UQ_USERS_1 (EMAIL_ADDR),
  PRIMARY KEY (USER_ID)
);
CREATE TABLE GROUPS(
	GROUP_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT, 
	GROUP_NAME  VARCHAR (255) NOT NULL,
	UNIQUE UQ_GROUPS_1 (GROUP_NAME),
	PRIMARY KEY (GROUP_ID)
);
CREATE TABLE USER_GROUP (
  USER_GROUP_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID INT(10) UNSIGNED NOT NULL,
  GROUP_ID INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (USER_GROUP_ID),
  KEY FK_USER_GROUP_1 (USER_ID),
  KEY FK_USER_GROUP_2 (GROUP_ID),
  CONSTRAINT FK_USER_GROUP_1 FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
  CONSTRAINT FK_USER_GROUP_2 FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (GROUP_ID)
);